export default {
  personal: [
    {
      name: 'Price Off',
      tag: 'Javascript, VueJS, Vuex, Framework7, Cordova',
      description: 'A hybrid app for browsing specials and discount in Australian grocery stores (Coles, Woolworths and Chemist Warehouse). The app helps you save your money. <br>For more info about the app, please visit <a target="_blank" href=https://github.com/freddysu/PriceOff>Price Off</a>.',
      imgSrc: 'priceoff',
      numOfImg: 5,
      androidLink: 'https://play.google.com/store/apps/details?id=com.goodprice.happylife.priceoff',
      iOSLink: 'https://apps.apple.com/us/app/price-off-groceries-discount/id1450076511',
      orientation: 'portrait',
      achievement: '',
    }
  ],
  work: [
    {
      name: 'Arcade Web',
      tag: 'JavaScript, React, Redux',
      description: 'Arcade web provides users for viewing their own posts including screenshots and videos uploaded from <a target="_blank" href=https://play.google.com/store/apps/details?id=mobisocial.arcade&hl=zh_TW>Omlet Arcade</a>. <a target="_blank" href=https://play.google.com/store/apps/details?id=mobisocial.arcade&hl=zh_TW>Omlet Arcade</a> is a live streaming and game recording app for mobile devices. It also provides users the hot and latest posts from other game players. I was in charge of the front-end development of arcade web application with my colleague while working at <a target="_blank" href="https://arcade.omlet.me/">Omlet Inc.</a> The web is implemented by React & Redux.',
      imgSrc: 'arcadeweb',
      numOfImg: 5,
      androidLink: null,
      iOSLink: '',
      orientation: 'landscape',
      achievement: '',
    },
    {
      name: 'Automated Testing System',
      tag: 'JavaScript, React, NodeJS, MongoDB, Calabash, Cucumber',
      description: 'The system helps our QA to run <a target="_blank" href="http://calaba.sh/">Calabash</a> testing on multiple devices simultaneously without knowing the Calabash commands. It makes QA to be more efficient at running commands and reviewing the test reports by providing a friendly web UI. I was responsible for this project at <a target="_blank" href="https://arcade.omlet.me/">Omlet Inc</a>.',
      imgSrc: 'autotest',
      numOfImg: 5,
      androidLink: null,
      iOSLink: '',
      orientation: 'landscape',
      achievement: '',
    },
    {
      name: 'Crawlers Monitor',
      tag: 'JavaScript, AngularJS, NodeJS, MongoDB',
      description: 'It\'s a crawlers monitor system I built by the time I was doing my summer internship (July 2015 - Sep. 2015) at <a target="_blank" href="http://www.thetrigger.io/">MobiusBobs</a>. Since we have lots of crawlers need to manage, it\'s really inconvenient to do all the operations with shell commands. The purpose of this system is to ease the pain of operating and monitoring crawlers by providing a web UI. Operations include signup, login/logout authentication, connecting to a target server by ssh, creating/removing/listing the crawlers, doing git pull/checkout, etc. The system is implemented by MEAN (MongoDB, Express, AngularJS, NodeJS).',
      imgSrc: 'monitor',
      numOfImg: 5,
      androidLink: null,
      iOSLink: '',
      orientation: 'landscape',
      achievement: '',
    },
    {
      name: 'Let\'s Ubike (Ubike 讓我騎)',
      tag: 'Java, Android',
      description: 'I was responsible for Android developement of this project while doing my internship (July 2013 - Jan. 2014) at <a target="_blank" href="http://www.chocolabs.com/">CHOCOLABS</a>. The app aims at providing user-friendly interfaces and real time information including stops location, navigation, number of available bikes, spaces, estimated waiting time and a timer. The app leverages Google Maps and Google Street View APIs to provide users the best service.',
      imgSrc: 'ubike',
      androidLink: 'https://play.google.com/store/apps/details?id=com.chocolabs.ubike',
      numOfImg: 5,
      iOSLink: '',
      orientation: 'portrait',
      achievement: '<ul><li>Wins the 11th Public Departmental Resources Application Award hosted by Industrial Development Bureau, MOEA</li><li>Downloads: 50,000 ~ 100,000</li></ul>',
    }
  ],
  school: [
    {
      name: 'Mobile Application Management',
      tag: 'JavaScript, Python, NodeJS, Neo4j',
      description: 'This is a system based on the client-server architecture and a graph database to analyze the capability of each application in a mobile device. The configuration extractor installed in the mobile device extracts APKs and system information, and uploads them to the server through RESTful API. After a series of APK decompiling, analysis and parsing, the information is organized and structured in the configuration graph database. Lastly, our system reports the device configuration information and potential vulnerabilities back to the user. The web server, APKs analyser, graph database are implemented by NodeJS, Python and Neo4j respectively.',
      imgSrc: 'mam',
      numOfImg: 4,
      androidLink: null,
      iOSLink: '',
      orientation: 'landscape',
      achievement: '',
    },
    {
      name: 'Hoppa Ellie',
      tag: 'C#, Unity3D',
      description: 'This is our game project from Software Engineering Process at Chalmer University of Technology. This game is built by Unity3D engine version 5.01. In this game, the player control the role, Ellie, to explore the world and reach the end goal. Hoppa Ellie is similar to SuperMario. The main difference is that player is not allow to stop Ellie from running but can only make Ellie jump over all the dangers coming to her.',
      imgSrc: 'hoppa',
      numOfImg: 5,
      androidLink: null,
      iOSLink: '',
      orientation: 'landscape',
      achievement: '',
    }
  ]
};